NAME = avscale

HEADERS = avscale.h

OBJS = avscale.o                                                        \
       internal.o                                                       \
       utils.o                                                          \

